name:                nazuki
version:             0.1.0.0
github:              "n4o847/nazuki-hs"
license:             MIT
author:              "n4o847"
maintainer:          "22975590+n4o847@users.noreply.github.com"
copyright:           "2019 n4o847"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/n4o847/nazuki-hs>

dependencies:
- base
- bytestring
- containers
- megaparsec
- mtl
- parser-combinators
- text

library:
  source-dirs: src

executables:
  nazuki:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nazuki

# Since Stack forces all executables to be built once,
# disable the wasm build here during CI.
# NAZUKI_WASM_BEGIN
  nazuki-wasm:
    main:                Main.hs
    source-dirs:         wasm
    ghc-options:
    - -no-hs-main
    - -optl-mexec-model=reactor
    - "\
      -optl-Wl,\
      --export=hs_init,\
      --export=malloc,\
      --export=free,\
      --export=compile,\
      --export=assemble,\
      --export=run,\
      --export=createBanner"
    dependencies:
    - nazuki
# NAZUKI_WASM_END

tests:
  nazuki-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nazuki
    - hspec

benchmarks:
  nazuki-bench:
    main:                Main.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nazuki
    - criterion
