name:                nazuki
version:             0.1.0
github:              "n4o847/nazuki-hs"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/n4o847/nazuki-hs>

dependencies:
- base >= 4.7 && < 5
- containers
- mtl
- text
- utf8-string

library:
  source-dirs: src

executables:
  nazuki:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nazuki

tests:
  nazuki-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nazuki
    - hspec
