name: CI

on:
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - 'app/**'
      - 'bench/**'
      - 'src/**'
      - 'test/**'
      - 'wasm/**'
      - 'stack.yaml'
      - 'stack.yaml.lock'
      - '*.cabal'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci.yml'
      - 'app/**'
      - 'bench/**'
      - 'src/**'
      - 'test/**'
      - 'wasm/**'
      - 'stack.yaml'
      - 'stack.yaml.lock'
      - '*.cabal'
  workflow_dispatch:

jobs:
  cabal-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: haskell-actions/setup@v2
        id: setup
        with:
          ghc-version: '9.8'

      - name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
        uses: actions/cache@v3
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-cabal-${{ steps.setup.outputs.cabal-version }}-${{ hashFiles('**/*.cabal', '**/cabal.project', '**/cabal.project.freeze') }}
          restore-keys: ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-cabal-${{ steps.setup.outputs.cabal-version }}-

      - run: |
          cabal test --test-show-detail=direct

  stack-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-no-global: true

      - uses: actions/cache@v3
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-global-${{ hashFiles('stack.yaml') }}-${{ hashFiles('*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-stack-global-

      - uses: actions/cache@v3
        name: Cache .stack-work
        with:
          path: .stack-work
          key: ${{ runner.os }}-stack-work-${{ hashFiles('stack.yaml') }}-${{ hashFiles('*.cabal') }}-${{ hashFiles('**/*.hs') }}
          restore-keys: |
            ${{ runner.os }}-stack-work-

      - run: |
          stack test
