name: CI

on:
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - 'app/**'
      - 'bench/**'
      - 'src/**'
      - 'test/**'
      - 'wasm/**'
      - 'hie.yaml'
      - '*.cabal'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci.yml'
      - 'app/**'
      - 'bench/**'
      - 'src/**'
      - 'test/**'
      - 'wasm/**'
      - 'hie.yaml'
      - '*.cabal'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: haskell/actions/setup@v2
        id: setup
        with:
          ghc-version: '9.6'

      - name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
        uses: actions/cache@v3
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-cabal-${{ steps.setup.outputs.cabal-version }}-${{ hashFiles('**/*.cabal', '**/cabal.project', '**/cabal.project.freeze') }}
          restore-keys: ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-cabal-${{ steps.setup.outputs.cabal-version }}-

      - run: |
          cabal test --test-show-detail=direct
