name: CI

on:
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - 'app/**'
      - 'bench/**'
      - 'src/**'
      - 'test/**'
      - 'wasm/**'
      - 'hie.yaml'
      - 'package.yaml'
      - 'stack.yaml'
      - 'stack.yaml.lock'
      - '*.cabal'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci.yml'
      - 'app/**'
      - 'bench/**'
      - 'src/**'
      - 'test/**'
      - 'wasm/**'
      - 'hie.yaml'
      - 'package.yaml'
      - 'stack.yaml'
      - 'stack.yaml.lock'
      - '*.cabal'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: haskell/actions/setup@v2
        with:
          enable-stack: true
          stack-no-global: true

      - uses: actions/cache@v3
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-global-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-global-

      - uses: actions/cache@v3
        name: Cache .stack-work
        with:
          path: .stack-work
          key: ${{ runner.os }}-stack-work-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}-${{ hashFiles('**/*.hs') }}
          restore-keys: |
            ${{ runner.os }}-stack-work-

      - run: |
          sed -i -e '/NAZUKI_WASM_BEGIN/,/NAZUKI_WASM_END/d' package.yaml
          stack test
