name: Experimental Workflow

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - run: git update-index --add --chmod=+x ./entrypoint.sh

      - name: Build
        uses: docker://terrorjack/asterius
        with:
          entrypoint: ./entrypoint.sh
